---
networks:
  gamutrf:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
  default:
    external: true
    name: none
services:
  waterfall:
    restart: unless-stopped
    # image: iqtlabs/gamutrf-waterfall:v0.5.65
    image: iqtlabs/gamutrf-waterfall
    build: 
      context: /home/ltindall/iqt/gamutRF
      dockerfile: /home/ltindall/iqt/gamutRF/docker/Dockerfile.waterfall
    pull_policy: build
    networks:
      - gamutrf
    ports:
      - '9003:9003'
    volumes:
      - '${VOL_PREFIX}:/logs'
    command:
      - gamutrf-waterfall
      - --api_endpoint=${GAMUTRF}:9001
      - --scanners=${GAMUTRF}:10000
      - --port=9003
      - --refresh=1
      
      # - --inference_server=${GAMUTRF}
      # - --inference_port=10001
      # - --save_path=/logs/waterfall
      # - --detection_type=narrowband
      # - --n_detect=1
      # - --width=12
      # - --height=6
      # - --min_freq=0
      # - --max_freq=0
      
